---
sidebar: sidebar 
permalink: vcp_task_reports_qossioc.html 
summary: Vous pouvez afficher des informations sur les sessions iSCSI connectées au cluster sélectionné dans le plug-in NetApp Element pour VMware vCenter Server. 
keywords: netapp, hci, vcp, vcenter, element, monitor, report, qossioc, cluster, performance 
---
= Surveiller la hiérarchisation des performances des machines virtuelles à l'aide des événements QoSSIOC
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher les événements liés à QoSSIOC lorsqu'une machine virtuelle dotée d'un datastore compatible QoS est reconfigurée ou émise lors d'un événement d'alimentation ou invité.

Vous pouvez afficher les événements QoSSIOC à partir du point d'extension du plug-in dans le plug-in NetApp Element pour vCenter Server.

Les événements QoSSIOC sont affichés à partir de clusters ajoutés localement. Dans un environnement en mode lié, connectez-vous au client Web vSphere auquel le cluster est ajouté localement pour afficher les événements QoSSIOC pour ce cluster.

[NOTE]
====
* À partir de la version 5.0 du plug-in Element vCenter, pour une utilisation link:vcp_concept_linkedmode.html["Mode lié vCenter"], Vous enregistrez le plug-in Element à partir d'un nœud de gestion distinct pour chaque serveur vCenter qui gère les clusters de stockage NetApp SolidFire.
* Utilisation du plug-in NetApp Element pour vCenter Server 4.10 et versions antérieures pour gérer les ressources du cluster à partir d'autres serveurs vCenter à l'aide de link:vcp_concept_linkedmode.html["Mode lié vCenter"] est limitée aux clusters de stockage locaux uniquement.


====
.Ce dont vous avez besoin
* Vous devez ajouter un cluster et en cours d'exécution au moins.
* Le service QoSSIOC doit être configuré et vérifié en cours d’exécution à l’aide de la page QoSSIOC Settings du plug-in.
* L'automatisation QoSSIOC doit être activée pour au moins un datastore.


.Étapes
. Dans votre client Web vSphere, ouvrez l'onglet *QoSSIOC Events* :
+
** En commençant par le plug-in Element vCenter 5.0, sélectionnez *NetApp Element Remote Plugin > Configuration > Evénements QoSSIOC*.
** Pour le plug-in Element vCenter 4.10 et les versions antérieures, sélectionnez *Configuration NetApp Element > Evénements QoSSIOC*.






== Données d'événement QoSSIOC

* *Date* : la date et l'heure de l'événement QoSSIOC.
* *Nom du datastore* : nom du datastore défini par l'utilisateur.
* *IP du cluster* : adresse IP du cluster contenant le datastore à partir duquel l'événement a été créé.
* *ID de volume* : ID généré par le système pour le volume associé.
* *Min IOPS* : paramètre de qualité de service minimum actuel du volume.
* *IOPS max* : paramètre de qualité de service d'IOPS maximum actuel du volume.
* *Burst IOPS* : le paramètre actuel de qualité de service maximale en rafale du volume.
* *Temps de rafale*: La durée d'une rafale est autorisée.




== Trouvez plus d'informations

* https://docs.netapp.com/us-en/hci/index.html["Documentation NetApp HCI"^]
* https://www.netapp.com/data-storage/solidfire/documentation["Page Ressources SolidFire et Element"^]

