---
sidebar: sidebar 
permalink: vcp_task_create_manage_user_accounts.html 
summary: 'Vous pouvez créer et gérer des comptes utilisateur à l"aide du plug-in.' 
keywords: netapp, storage, accounts, vcp, vcenter, element 
---
= Créer et gérer des comptes utilisateur
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:vcp_concept_accounts.html["Comptes d'utilisateur"] Permettent de contrôler l'accès aux ressources de stockage sur un réseau logiciel NetApp Element.

.Options
*  an account
*  an account
*  an account




== Créez un compte

Vous pouvez créer un compte utilisateur unique pour autoriser l'accès aux volumes de stockage.

.Ce dont vous avez besoin, 8217;ll
* Vous devez ajouter un cluster et en cours d'exécution au moins.


.Étapes
. Dans votre client Web vSphere, ouvrez l'onglet *Management* :
+
** Depuis le plug-in Element vCenter 5.0, sélectionnez *NetApp Element Remote Plugin > Management > Management*.
** Pour le plug-in Element vCenter 4.10 et les versions antérieures, sélectionnez *NetApp Element Management > Management*.


+

NOTE: Si deux clusters ou plus sont ajoutés, assurez-vous que le cluster que vous souhaitez utiliser pour la tâche est sélectionné dans la barre de navigation.

. Sélectionnez le sous-onglet *comptes*.
. Sélectionnez *Créer un compte*.
. Entrez un nom d'utilisateur.
+

TIP: Utilisez les bonnes pratiques descriptives en matière de dénomination. Ceci est particulièrement important si plusieurs clusters ou serveurs vCenter sont utilisés dans votre environnement.

. Dans la section *CHAP Settings* :
+
.. Saisissez le secret d'initiateur pour l'authentification de session de nœud CHAP.
.. Saisissez le secret cible pour l'authentification de session de nœud CHAP.
+

NOTE: Les secrets d'initiateur et de cible doivent être différents. Si ces champs ne sont pas renseignés, le système génère les informations d'authentification.



. Cliquez sur *OK* pour créer le compte.




== Modifier un compte

Vous pouvez modifier un compte utilisateur pour modifier le statut ou les secrets CHAP. La modification des paramètres CHAP peut entraîner une perte de connectivité entre un hôte et ses volumes associés.

Si vous utilisez des volumes persistants avec le nœud de gestion, ne modifiez pas le nom du compte associé à ces volumes.

.Étapes
. Dans votre client Web vSphere, ouvrez l'onglet *Management* :
+
** Depuis le plug-in Element vCenter 5.0, sélectionnez *NetApp Element Remote Plugin > Management > Management*.
** Pour le plug-in Element vCenter 4.10 et les versions antérieures, sélectionnez *NetApp Element Management > Management*.


+

NOTE: Si deux clusters ou plus sont ajoutés, assurez-vous que le cluster que vous souhaitez utiliser pour la tâche est sélectionné dans la barre de navigation.

. Sélectionnez le sous-onglet *comptes*.
. Cochez la case correspondant au compte que vous souhaitez modifier.
. Sélectionnez *actions*.
. Dans le menu qui s'affiche, sélectionnez *Modifier*.
. Modifiez les éléments suivants si nécessaire :
+
.. Modifiez l'état d'accès du compte.
+

IMPORTANT: La modification de l'accès à *Locked* met fin à toutes les connexions iSCSI du compte et le compte n'est plus accessible. Les volumes associés au compte sont conservés, mais ils ne sont pas détectables iSCSI.

.. Modifiez les informations d'identification secrètes d'initiateur ou de cible utilisées pour l'authentification d'une session de nœud.
+

NOTE: Si vous ne modifiez pas les informations d'identification, elles restent les mêmes. Si vous ne renseignez pas les champs d'informations d'identification, le système génère de nouveaux mots de passe.



. Cliquez sur *OK*.




== Supprimer un compte

Vous pouvez supprimer des comptes utilisateur à l'aide du point d'extension du plug-in.

Supprimez et supprimez tout volume associé au compte ou réaffectez-le à un autre compte.


IMPORTANT: Si vous utilisez des volumes persistants avec le nœud de gestion, ne supprimez pas le compte associé à ces volumes.

.Étapes
. Dans votre client Web vSphere, ouvrez l'onglet *Management* :
+
** Depuis le plug-in Element vCenter 5.0, sélectionnez *NetApp Element Remote Plugin > Management > Management*.
** Pour le plug-in Element vCenter 4.10 et les versions antérieures, sélectionnez *NetApp Element Management > Management*.


+

NOTE: Si deux clusters ou plus sont ajoutés, assurez-vous que le cluster que vous souhaitez utiliser pour la tâche est sélectionné dans la barre de navigation.

. Sélectionnez le sous-onglet *comptes*.
. Cochez la case correspondant au compte que vous souhaitez supprimer.
. Cliquez sur *actions*.
. Dans le menu qui s'affiche, sélectionnez *Supprimer*.
. Confirmez l'action.




== Trouvez plus d'informations

* https://docs.netapp.com/us-en/hci/index.html["Documentation NetApp HCI"^]
* https://www.netapp.com/data-storage/solidfire/documentation["Page Ressources SolidFire et Element"^]

