---
sidebar: sidebar 
permalink: vcp_reference_reports_alert_errors.html 
summary: 'La liste des alertes système, à savoir des informations, des avertissements ou des erreurs qui indiquent la qualité d"exécution du cluster à l"aide des pages de reporting du plug-in NetApp Element pour VMware vCenter Server, s"affiche ci-dessous.' 
keywords: netapp, hci, vcp, vcenter, element, monitor, report, alert, cluster, performance 
---
= Liste des alertes système
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: media/


[role="lead"]
Le système signale les codes d'erreur avec chaque alerte qui vous aide à déterminer quel composant du système a rencontré l'alerte et pourquoi l'alerte a été générée. Vous pouvez afficher les codes d'erreur à l'aide du point d'extension du plug-in :

* Depuis le plug-in Element vCenter 5.0, sélectionnez *NetApp Remote Plugin > gestion > Reporting > alertes*.
* Pour le plug-in Element vCenter 4.10 et les versions antérieures, sélectionnez *gestion NetApp Element > Rapports > alertes*.


La liste suivante présente les différents types d'alertes système.

* *AuthenticationServiceFault* : le service d'authentification sur un ou plusieurs nœuds de cluster ne fonctionne pas comme prévu.
+
*À résoudre* : contactez le support NetApp pour obtenir de l'aide.

* *DisponibleVirtualNetworkIPAddresssLow* : le nombre d'adresses de réseau virtuel dans le bloc d'adresses IP est faible.
+
*Pour résoudre* : ajoutez d'autres adresses IP au bloc d'adresses de réseau virtuel.

* *BlockClusterFull*: Il n'y a pas assez d'espace libre de stockage en bloc pour prendre en charge une perte de nœud unique. Pour plus de détails sur les niveaux de remplissage du cluster, reportez-vous à la méthode GetClusterFullThreshold API. Cette panne du cluster indique l'une des conditions suivantes :
+
** Stage3Low (Avertissement) : le seuil défini par l'utilisateur a été franchi. Réglez les paramètres Cluster Full ou ajoutez des nœuds.
** Stage4Critique (erreur) : l'espace disponible pour la restauration suite à une défaillance d'un nœud est insuffisant. La création de volumes, de snapshots et de clones n'est pas autorisée.
** Stage5CompletelyConsumied (critique)1 ; aucune écriture ni aucune nouvelle connexion iSCSI ne sont autorisées. Les connexions iSCSI actuelles seront conservées. Les écritures échouent jusqu'à ce que davantage de capacité soit ajoutée au cluster.


+
*Pour résoudre* : purgez ou supprimez des volumes ou ajoutez un autre noeud de stockage au cluster de stockage.

* *BlockksDegaded*: Les données de bloc ne sont plus intégralement répliquées en raison d'une panne.
+
[cols="25,75"]
|===
| Gravité | Description 


| Avertissement | Seules deux copies complètes des données de bloc sont accessibles. 


| Erreur | Seule une seule copie complète des données du bloc est accessible. 


| Primordial | Aucune copie complète des données de bloc n'est accessible. 
|===
+

NOTE: L'état d'avertissement ne peut se produire que sur un système Triple Helix.

+
*À résoudre* : restaurez tout nœud hors ligne ou service de bloc, ou contactez le support NetApp pour obtenir de l'aide.

* *BlockServiceTooFull*: Un service de bloc utilise trop d'espace.
+
*Pour résoudre* : ajoutez plus de capacité provisionnée.

* *BlockServiceUnHealthy*: Un service de bloc a été détecté comme défectueux:
+
** Gravité = Avertissement : aucune action n'est entreprise. Cette période d'avertissement expire dans cTimeUntilBSIsKilledMsec=330000 millisecondes.
** Gravité = erreur : le système met automatiquement hors service les données et reréplique ses données sur d'autres lecteurs en bon état.
** Gravité = critique : des services de bloc défaillants sur plusieurs nœuds supérieurs ou égaux au nombre de réplications (2 pour la double hélice). Les données ne sont pas disponibles et la synchronisation des bacs ne se termine pas.


+
*Pour résoudre* : recherchez des problèmes de connectivité réseau et des erreurs matérielles. Il y aura d'autres défauts si des composants matériels spécifiques sont défectueux. Le défaut s'efface lorsque le service de bloc est accessible ou lorsque le service a été déclassé.

* *ClockewExceedsFaiultThreshold* : l'inclinaison du temps entre le maître de cluster et le nœud qui présente un jeton dépasse le seuil recommandé. Le cluster de stockage ne peut pas corriger automatiquement l'écart de temps entre les nœuds.
+
*Pour résoudre* : utilisez des serveurs NTP internes à votre réseau plutôt que les paramètres par défaut de l'installation. Si vous utilisez un serveur NTP interne, contactez le support NetApp pour obtenir de l'aide.

* *ClusterCannotSync* : il existe une condition de manque d'espace et les données sur les disques de stockage de blocs hors ligne ne peuvent pas être synchronisées avec les lecteurs qui sont toujours actifs.
+
*Pour résoudre*: Ajouter plus de stockage.

* *ClusterFull* : il n'y a plus d'espace de stockage libre dans le cluster de stockage.
+
*Pour résoudre*: Ajouter plus de stockage.

* *ClusterIOPSAreOverProvisioned* : les IOPS du cluster sont sur-provisionnées. La somme de toutes les IOPS minimales de QoS est supérieure aux IOPS attendues du cluster. Il est impossible de maintenir la qualité de service minimale pour tous les volumes simultanément.
+
*Pour résoudre* : réduisez les paramètres d'IOPS de qualité de service minimum pour les volumes.

* *DisableDriveSecurityFailed* : le cluster n'est pas configuré pour activer la sécurité du lecteur (chiffrement au repos), mais au moins un disque a la sécurité activée, ce qui signifie que la désactivation de la sécurité du lecteur sur ces lecteurs a échoué. Ce défaut est consigné avec la gravité “Avertissement”.
+
*Pour résoudre* : vérifiez les détails de l'erreur pour la raison pour laquelle la sécurité du lecteur n'a pas pu être désactivée. Les raisons possibles sont :

+
** La clé de chiffrement n'a pas pu être acquise, recherchez le problème d'accès à la clé ou au serveur de clés externe.
** L'opération de désactivation a échoué sur le lecteur, déterminez si la mauvaise clé a pu être acquise.


+
Si aucun de ces éléments n'est la cause du défaut, il est possible que le lecteur doive être remplacé. Vous pouvez tenter de récupérer un lecteur qui ne désactive pas la sécurité avec succès, même lorsque la clé d'authentification correcte est fournie. Pour effectuer cette opération, retirez le ou les lecteurs du système en les déplaçant vers disponibles, effectuez une suppression sécurisée sur le lecteur et revenez à actif.

* *DisconnectedClusterpair* : une paire de clusters est déconnectée ou configurée de façon incorrecte.
+
*Pour résoudre* : vérifiez la connectivité réseau entre les clusters.

* *DisconnectedRemoteNode* : un noeud distant est soit déconnecté soit mal configuré.
+
*Pour résoudre* : vérifiez la connectivité réseau entre les nœuds.

* *DisconnectedSnapMirror orEndpoint* : un noeud final SnapMirror distant est déconnecté ou configuré de manière incorrecte.
+
*À résoudre* : vérifiez la connectivité réseau entre le cluster et le point de terminaison SnapMirror distant.

* *DriveAvailable*: Un ou plusieurs lecteurs sont disponibles dans le cluster. En général, tous les clusters doivent avoir tous des disques ajoutés ou aucun disque n'est à l'état disponible. Si ce défaut apparaît de façon inattendue, contactez le support NetApp.
+
*Pour résoudre* : ajoutez tout disque disponible au cluster de stockage.

* *RaveFailed* : le cluster renvoie cette erreur lorsqu'un ou plusieurs disques sont défaillants, ce qui indique l'une des conditions suivantes :
+
** Le gestionnaire de lecteur ne peut pas accéder au lecteur.
** Le service de tranche ou de bloc a échoué trop de fois, probablement à cause des échecs de lecture ou d'écriture du disque, et ne peut pas redémarrer.
** Le lecteur est manquant.
** Le service maître du nœud est inaccessible (tous les disques du nœud sont considérés comme manquants/défaillants).
** Le lecteur est verrouillé et la clé d'authentification du lecteur ne peut pas être acquise.
** Le lecteur est verrouillé et l'opération de déverrouillage échoue.


+
*Pour résoudre*:

+
** Vérifiez la connectivité réseau du nœud.
** Remplacez le lecteur.
** Assurez-vous que la clé d'authentification est disponible.


* *DriveHealthFault* : un lecteur a échoué à la vérification de l'état SMART et par conséquent, les fonctions du lecteur sont réduites. Il existe un niveau de gravité critique pour ce défaut :
+
** Disque avec le numéro de série : <numéro de série> dans le slot : <slot de nœud><slot de disque> a échoué au contrôle global INTELLIGENT de l'état du disque.


+
*Pour résoudre* : remplacez le lecteur.

* *DriveWeearFault* : la durée de vie restante d'un disque est tombée en dessous des seuils, mais il fonctionne toujours. Il existe deux niveaux de gravité possibles pour ce défaut : critique et avertissement :
+
** Disque en série : <numéro de série> dans le slot : <slot de nœud><slot de disque> présente des niveaux d'usure stratégiques.
** Disque avec série : <numéro de série> dans le slot : <slot de nœud><slot de disque> présente une faible usure.


+
*Pour résoudre* : pour résoudre ce problème, remplacez le lecteur bientôt.

* *DuplicateClusterMasterCandidates*: Plus d'un candidat maître de cluster de stockage a été détecté.
+
*À résoudre* : contactez le support NetApp pour obtenir de l'aide.

* *EnableDriveSecurityFailed* : le cluster est configuré pour exiger la sécurité du disque (chiffrement au repos), mais la sécurité du disque n'a pas pu être activée sur au moins un disque. Ce défaut est consigné avec la gravité “Avertissement”.
+
*Pour résoudre* : vérifiez les détails de l'erreur pour la raison pour laquelle la sécurité du lecteur n'a pas pu être activée. Les raisons possibles sont :

+
** La clé de chiffrement n'a pas pu être acquise, recherchez le problème d'accès à la clé ou au serveur de clés externe.
** L'opération d'activation a échoué sur le lecteur, déterminez si la clé incorrecte a pu être acquise.
+
Si aucun de ces éléments n'est la cause du défaut, il est possible que le lecteur doive être remplacé.



+
Vous pouvez tenter de récupérer un lecteur qui n'active pas la sécurité avec succès, même lorsque la clé d'authentification correcte est fournie. Pour effectuer cette opération, retirez le ou les lecteurs du système en les déplaçant vers disponibles, effectuez une suppression sécurisée sur le lecteur et revenez à actif.

* *EnsembleDegaded*: La connectivité ou l'alimentation réseau a été perdue à un ou plusieurs des noeuds de l'ensemble.
+
*Pour résoudre* : pour résoudre ce problème, restaurez la connectivité ou l'alimentation réseau.

* *Exception* : un défaut signalé qui n'est pas un défaut de routine. Ces défauts ne sont pas automatiquement effacés de la file d'attente des pannes.
+
*Pour résoudre le problème* contactez le support NetApp pour obtenir de l'aide.

* *FailedSpaceTooFull*: Un service de bloc ne répond pas aux demandes d'écriture de données. Le service de tranche est alors à court d'espace pour stocker les écritures ayant échoué.
+
*Pour résoudre* : pour résoudre ce défaut, restaurez la fonctionnalité des services de bloc pour permettre aux écritures de continuer normalement et l'espace non disponible pour être vidé du service de tranche.

* *FanSensor* : un capteur de ventilateur est défectueux ou manquant.
+
*Pour résoudre* : pour résoudre ce problème, remplacez tout matériel défectueux.

* *FibroChannelAccessDegraded*: Un nœud Fibre Channel ne répond pas à d'autres nœuds du cluster de stockage sur son IP de stockage pendant un certain temps. Dans cet état, le nœud est alors considéré comme ne répond pas et génère une panne du cluster.
+
*Pour résoudre* : vérifier la connectivité réseau.

* *FibroChannelAccessUnavailable*: Tous les nœuds Fibre Channel ne répondent pas. Les ID de nœud sont affichés.
+
*Pour résoudre* : vérifier la connectivité réseau.

* *FibroChannelActiveIxL* : le nombre de commutateurs iXL Nexus approche la limite prise en charge de 8000 sessions actives par nœud Fibre Channel.
+
** La limite des bonnes pratiques est de 5500.
** La limite d'avertissement est de 7500.
** La limite maximale (non appliquée) est de 8192.


+
*À résoudre*: TInterduire le nombre de Nexus iXL inférieur à la limite des meilleures pratiques de 5500.

* *FibroChannelConfig* : ce défaut du groupe d'instruments indique l'une des conditions suivantes :
+
** Un port Fibre Channel inattendu est installé sur un slot PCI.
** Il existe un modèle HBA Fibre Channel inattendu.
** Il y a un problème avec le firmware d'un HBA Fibre Channel.
** Un port Fibre Channel n'est pas en ligne.
** Il existe un problème persistant de configuration du mot de passe Fibre Channel.


+
*À résoudre* : contactez le support NetApp pour obtenir de l'aide.

* *FibroChannelIOPS* : le nombre total d'IOPS approche de la limite d'IOPS pour les nœuds Fibre Channel du cluster. Les limites sont les suivantes :
+
** FC0025 : limite de 450 000 IOPS à une taille de bloc de 4 Ko par nœud Fibre Channel.
** FCN001 : limite d'opérations de 625 000 IOPS à une taille de bloc de 4 Ko par nœud Fibre Channel.


+
*Pour résoudre* : pour résoudre ce problème, équilibrer la charge sur tous les nœuds Fibre Channel disponibles.

* *FibroChannelStaticIxL* : le nombre iXL Nexus approche la limite prise en charge de 16000 sessions statiques par nœud Fibre Channel.
+
** La limite des bonnes pratiques est de 11000.
** La limite d'avertissement est de 15000.
** La limite maximale (appliquée) est de 16384.


+
*Pour résoudre*: Pour résoudre ce défaut, réduire le nombre de Nexus iXL inférieur à la limite de la meilleure pratique de 11000.

* *FileSystemCapacityLow*: Il y a un espace insuffisant sur l'un des systèmes de fichiers.
+
*Pour résoudre*: Ajouter plus de capacité au système de fichiers.

* *FipsDriveMissmatch* : un lecteur non FIPS a été physiquement inséré dans un nœud de stockage compatible FIPS ou un lecteur FIPS a été physiquement inséré dans un nœud de stockage non FIPS. Une seule panne est générée par nœud et répertorie tous les disques affectés.
+
*Pour résoudre* : pour résoudre ce problème, retirez ou remplacez le ou les lecteurs non concordants en question.

* *FipsDriveOutOfCompliance* : le système a détecté que le chiffrement au repos était désactivé après l'activation de la fonction lecteurs FIPS. Cette panne est également générée lorsque la fonctionnalité lecteurs FIPS est activée et qu'un lecteur ou nœud non FIPS est présent dans le cluster de stockage.
+
*Pour résoudre* : activez le chiffrement au repos ou retirez le matériel non-FIPS du cluster de stockage.

* *FipsSelfTestFailure* : le sous-système FIPS a détecté une défaillance pendant l'auto-test.
+
*À résoudre* : contactez le support NetApp pour obtenir de l'aide.

* *HardwareConfigMismatch* : ce défaut de groupe d'instruments indique l'une des conditions suivantes :
+
** La configuration ne correspond pas à la définition du nœud.
** La taille de disque de ce type de nœud est incorrecte.
** Un lecteur non pris en charge a été détecté. Une raison possible est que la version de l'élément installé ne reconnaît pas ce lecteur. Il est recommandé de mettre à jour le logiciel Element sur ce nœud.
** Le firmware du disque ne correspond pas.
** L'état compatible du cryptage de disque ne correspond pas au nœud.


+
*À résoudre* : contactez le support NetApp pour obtenir de l'aide.

* *IdPCertificateExpérired* : le certificat SSL du fournisseur de services du cluster pour utilisation avec un fournisseur d'identité tiers (IDP) arrive à expiration ou a déjà expiré. Ce défaut utilise les niveaux de gravité suivants en fonction de l'urgence :
+
[cols="25,75"]
|===
| Gravité | Description 


| Avertissement | Le certificat expire dans un délai de 30 jours. 


| Erreur | Le certificat expire dans un délai de 7 jours. 


| Primordial | Le certificat expire dans un délai de 3 jours ou a déjà expiré. 
|===
+
*Pour résoudre* : pour résoudre cette erreur, mettez à jour le certificat SSL avant qu'il n'expire. Utilisez le `UpdateIdpConfiguration` Méthode API avec `refreshCertificateExpirationTime=true` Fournir le certificat SSL mis à jour.

* *InConsistenBondmodes* : les modes de liaison sur le périphérique VLAN sont manquants. Ce défaut affiche le mode de liaison attendu et le mode de liaison en cours d'utilisation.
* *Inconstant Mtus* : cette défaillance du bloc d'instruments indique l'une des conditions suivantes :
+
** Bond1G non-concordance : des MTUs incohérents ont été détectés sur les interfaces Bond1G.
** Bond10G : des MTUs incohérents ont été détectés sur les interfaces Bond10G.


+
Cette erreur affiche le ou les nœuds en question ainsi que la valeur MTU associée.

* *InConsistenRoutingRules* : les règles de routage de cette interface sont incohérentes.
* *InConsistenSubnetmasques* : le masque de réseau sur le périphérique VLAN ne correspond pas au masque de réseau enregistré en interne pour le VLAN. Ce défaut affiche le masque de réseau attendu et le masque de réseau actuellement utilisé.
* *IncorrictBondPortCount* : le nombre de ports de liaison est incorrect.
* *InvalidConfiguredFibreChannelNodeCount*: L'une des deux connexions de nœud Fibre Channel attendues est dégradé. Cette erreur s'affiche lorsqu'un seul nœud Fibre Channel est connecté.
+
*Pour résoudre* : vérifiez la connectivité réseau du cluster et le câblage réseau et recherchez les services défaillants. En l'absence de problèmes de réseau ou de service, contactez le support NetApp pour obtenir un remplacement de nœud Fibre Channel.

* *IrqBalanceed*: Une exception s'est produite lors de la tentative d'équilibrage des interruptions.
+
*À résoudre* : contactez le support NetApp pour obtenir de l'aide.

* *KmipCertificateFault* :
+
** Le certificat de l'autorité de certification racine (AC) arrive à expiration.
+
*Pour résoudre*: Pour résoudre cette erreur, acquérir un nouveau certificat de l'autorité de certification racine avec une date d'expiration d'au moins 30 jours et utiliser ModityKeyServerKmip pour fournir le certificat d'autorité de certification racine mis à jour.

** Le certificat client arrive à expiration.
+
*Pour résoudre*: Pour résoudre cette erreur, créez une nouvelle RSC à l'aide de GetClientCertificateSigningRequest, demandez-lui de vous assurer que la nouvelle date d'expiration est au moins 30 jours et utilisez ModityKeyServerKmip pour remplacer le certificat client KMIP arrivant à expiration par le nouveau certificat.

** Le certificat de l'autorité de certification racine (CA) a expiré.
+
*Pour résoudre*: Pour résoudre cette erreur, acquérir un nouveau certificat de l'autorité de certification racine avec une date d'expiration d'au moins 30 jours et utiliser ModityKeyServerKmip pour fournir le certificat d'autorité de certification racine mis à jour.

** Le certificat client a expiré.
+
*Pour résoudre*: Pour résoudre cette erreur, créez une nouvelle RSC à l'aide de `GetClientCertificateSigningRequest`, faites-le signer pour vous assurer que la nouvelle date d'expiration est au moins 30 jours à l'extérieur, et que l'utilisation est prévue `ModifyKeyServerKmip` Pour remplacer le certificat client KMIP expiré par le nouveau certificat.

** Erreur de certificat de l'autorité de certification racine (CA).
+
*Pour résoudre* : pour résoudre cette erreur, vérifiez que le certificat correct a été fourni et, si nécessaire, réacquérez le certificat à partir de l'autorité de certification racine. Utiliser `ModifyKeyServerKmip` Pour installer le certificat client KMIP approprié.

** Erreur de certificat client.
+
*Pour résoudre* : pour résoudre cette erreur, vérifiez que le certificat client KMIP correct est installé. L'autorité de certification racine du certificat client doit être installée sur le système EKS. Utiliser `ModifyKeyServerKmip` Pour installer le certificat client KMIP approprié.



* *KmipServerFault* :
+
** Échec de la connexion
+
*Pour résoudre* : pour résoudre ce problème, vérifiez que le serveur de clés externe est actif et accessible via le réseau. Utiliser `TestKeyServerKimp` et `TestKeyProviderKmip` pour tester votre connexion.

** Échec de l'authentification
+
*Pour résoudre* : pour résoudre cette erreur, vérifiez que les certificats de l'autorité de certification racine et du client KMIP corrects sont utilisés et que la clé privée et le certificat du client KMIP correspondent.

** Erreur du serveur
+
*Pour résoudre* : pour résoudre ce problème, vérifiez les détails de l'erreur. Le dépannage du serveur de clés externe peut être nécessaire en fonction de l'erreur renvoyée.



* *MemyEccThreshold*: Un grand nombre d'erreurs ECC corrigibles ou non corrigibles ont été détectées. Lorsqu'une erreur de gravité de type est renvoyée, cela est probablement dû à une panne de module DIMM.
+
*À résoudre* : contactez le support NetApp pour obtenir de l'aide.

* *MemoryUsageThreshold*: L'utilisation de la mémoire est supérieure à la normale. Ce défaut utilise les niveaux de gravité suivants en fonction de l'urgence :
+

NOTE: Voir le titre Détails pour plus d'informations sur le défaut.

+
[cols="25,75"]
|===
| Gravité | Description 


| Avertissement | La mémoire système est faible. 


| Erreur | La mémoire système est très faible. 


| Primordial | La mémoire système est totalement consommée. 
|===
+
*À résoudre* : contactez le support NetApp pour obtenir de l'aide.

* *MetadataClusterFull*: Il n'y a pas assez d'espace libre de stockage des métadonnées pour prendre en charge une perte de nœud unique. Voir la `GetClusterFullThreshold` Méthode API pour les détails sur les niveaux de remplissage du cluster. Cette panne du cluster indique l'une des conditions suivantes :
+
** Stage3Low (Avertissement) : le seuil défini par l'utilisateur a été franchi. Réglez les paramètres Cluster Full ou ajoutez des nœuds.
** Stage4Critique (erreur) : l'espace disponible pour la restauration suite à une défaillance d'un nœud est insuffisant. La création de volumes, de snapshots et de clones n'est pas autorisée.
** Stage5CompletelyConsumied (critique)1 ; aucune écriture ni aucune nouvelle connexion iSCSI ne sont autorisées. Les connexions iSCSI actuelles seront conservées. Les écritures échouent jusqu'à ce que davantage de capacité soit ajoutée au cluster. Supprimez ou supprimez des données ou ajoutez des nœuds.


+
*Pour résoudre* : purgez ou supprimez des volumes ou ajoutez un autre noeud de stockage au cluster de stockage.

* *MtuCheckFailure* : un périphérique réseau n'est pas configuré pour la taille de MTU appropriée.
+
*Pour résoudre* : assurez-vous que toutes les interfaces réseau et tous les ports de commutateur sont configurés pour les trames jumbo (MTUs jusqu'à 9000 octets).

* *NetworkConfig* : ce défaut du cluster indique l'une des conditions suivantes :
+
** Une interface attendue n'est pas présente.
** Une interface dupliquée est présente.
** Une interface configurée est en panne.
** Un redémarrage du réseau est nécessaire.


+
*À résoudre* : contactez le support NetApp pour obtenir de l'aide.

* *NoAvailableVirtualNetworkIPAddresses*: Il n'y a pas d'adresses de réseau virtuel disponibles dans le bloc d'adresses IP.
+
[listing]
----
 virtualNetworkID # TAG(###) has no available storage IP addresses. Additional nodes cannot be added to the cluster.
----
+
*Pour résoudre* : ajoutez d'autres adresses IP au bloc d'adresses de réseau virtuel.

* *NodeHardwareFault (l'interface réseau <nom> est en panne ou le câble est débranché)* : une interface réseau est en panne ou le câble est débranché.
+
*Pour résoudre* : vérifiez la connectivité réseau du ou des nœuds.

* *NodeHardwareFault (l'état de cryptage de disque compatible correspond à l'état de cryptage du nœud compatible pour le lecteur dans le logement <node slot><drive slot>)* : un lecteur ne correspond pas aux capacités de cryptage avec le nœud de stockage dans lequel il est installé.
* *NodeHardwareFault (<type de disque> taille du disque <taille réelle> pour le lecteur dans le logement <logement de nœud><logement de disque> pour ce type de nœud - attendue <taille attendue>)* : un nœud de stockage contient un lecteur de taille incorrecte pour ce nœud.
* *NodeHardwareFault (disque non pris en charge détecté dans le logement <logement de nœud><emplacement de lecteur> ; les statistiques de lecteur et les informations d'intégrité seront indisponibles)* : un nœud de stockage contient un lecteur qu'il ne prend pas en charge.
* *NodeHardwareFault (le lecteur dans le logement <logement de nœud><logement de lecteur> doit utiliser la version du micrologiciel <version attendue>, mais utilise une version non prise en charge <version réelle>)* : un nœud de stockage contient un lecteur exécutant une version de micrologiciel non prise en charge.
* *NodeMaintenanceMode* : un noeud a été placé en mode maintenance. Ce défaut utilise les niveaux de gravité suivants en fonction de l'urgence :
+
[cols="25,75"]
|===
| Gravité | Description 


| Avertissement | Indique que le nœud est toujours en mode de maintenance. 


| Erreur | Indique que le mode de maintenance n'a pas pu être désactivé, probablement en raison d'un standard actif ou défectueux. 
|===
+
*Pour résoudre* : désactivez le mode de maintenance une fois la maintenance terminée. Si le problème de niveau d'erreur persiste, contactez le support NetApp pour obtenir de l'aide.

* *NodeOffline* : le logiciel Element ne peut pas communiquer avec le nœud spécifié. Vérifiez la connectivité réseau.
* *NotUsingLACPBondMode* : le mode de liaison LACP n'est pas configuré.
+
*Pour résoudre*: Utiliser la liaison LACP lors du déploiement des nœuds de stockage; les clients peuvent rencontrer des problèmes de performances si LACP n'est pas activé et correctement configuré.

* *NtpServerUnreable* : le cluster de stockage ne peut pas communiquer avec le serveur ou les serveurs NTP spécifiés.
+
*Pour résoudre* : vérifiez la configuration du serveur NTP, du réseau et du pare-feu.

* *NtpTimeNotInSync* : la différence entre l'heure du cluster de stockage et celle du serveur NTP spécifié est trop importante. Le cluster de stockage ne peut pas corriger automatiquement la différence.
+
*Pour résoudre* : utilisez des serveurs NTP internes à votre réseau plutôt que les paramètres par défaut de l'installation. Si vous utilisez des serveurs NTP internes et que le problème persiste, contactez le support NetApp pour obtenir de l'aide.

* *NvramDeviceStatus* : un périphérique NVRAM a une erreur, est en panne ou a échoué. Ce défaut présente les niveaux de gravité suivants :
+
[cols="25,75"]
|===
| Gravité | Description 


| Avertissement | Un avertissement a été détecté par le matériel. Cette condition peut être transitoire, comme un avertissement de température. * NvmLifetimeError * nvmLifetimeStatus * energySourceLifetimeStatus * energySourceTempertureStatus * warningThresholdExceeemedistribution 


| Erreur | Une erreur ou un état critique a été détecté par le matériel. Le maître de cluster tente de supprimer le disque de coupe de l'opération (cela génère un événement de suppression de disque). Si les services de tranche secondaire ne sont pas disponibles, le lecteur ne sera pas supprimé. Erreurs renvoyées en plus des erreurs de niveau d'avertissement : * le point de montage du périphérique NVRAM n'existe pas. * La partition de périphérique NVRAM n'existe pas. * La partition de périphérique NVRAM existe mais n'est pas montée. 


| Primordial | Une erreur ou un état critique a été détecté par le matériel. Le maître de cluster tente de supprimer le disque de coupe de l'opération (cela génère un événement de suppression de disque). Si les services de tranche secondaire ne sont pas disponibles, le lecteur ne sera pas supprimé. * Persistance Lost * armStatusSaveNarmé * csaveStatusError 
|===
+
*Pour résoudre* : remplacez tout matériel défectueux dans le nœud. Si ce problème ne se résout pas, contactez le support NetApp pour obtenir de l'aide.

* *PowerSupplyError* : ce défaut du groupe d'instruments indique l'une des conditions suivantes :
+
** Aucune alimentation n'est présente.
** Un bloc d'alimentation est défectueux.
** Une entrée d'alimentation est manquante ou hors plage.
+
*Pour résoudre* : vérifiez que l'alimentation redondante est fournie à tous les nœuds. Contactez le support NetApp pour obtenir de l'aide.



* *Provisionne onedSpaceTooFull* : la capacité globale provisionnée du cluster est trop pleine.
+
*Pour résoudre* : ajoutez plus d'espace provisionné ou supprimez et purgez des volumes.

* *RemoteRepAsyncDelayExceema* : le délai asynchrone configuré pour la réplication a été dépassé. Vérifier la connectivité réseau entre les clusters.
* *RemoteRepClusterFull* : les volumes ont interrompu la réplication à distance car le cluster de stockage cible est trop plein.
+
*Pour résoudre* : libérez de l'espace sur le cluster de stockage cible.

* *RemoteRepSnapshotFull* : les volumes ont interrompu la réplication à distance des snapshots car le cluster de stockage cible est trop plein.
+
*Pour résoudre* : libérez de l'espace sur le cluster de stockage cible.

* *RemoteRepSnapshotsExceededLimit* : les volumes ont mis en pause la réplication distante des snapshots car le volume du cluster de stockage cible a dépassé sa limite de snapshots.
+
*Pour résoudre* : augmentez la limite d'instantané sur le cluster de stockage cible.

* *ScheduleActionError* : une ou plusieurs des activités planifiées ont été exécutées, mais ont échoué. Le défaut disparaît si l'activité programmée s'exécute de nouveau et réussit, si l'activité planifiée est supprimée ou si l'activité est interrompue et reprise.
* *SensoriReadiingFailé* : l'autotest du contrôleur BMC (Baseboard Management Controller) a échoué ou un capteur n'a pas pu communiquer avec le contrôleur BMC.
+
*À résoudre* : contactez le support NetApp pour obtenir de l'aide.

* *ServiceNotRunning* : un service requis n'est pas en cours d'exécution.
+
*À résoudre* : contactez le support NetApp pour obtenir de l'aide.

* *SliceServiceTooFull*: Un service de tranche a trop peu de capacité provisionnée qui lui est attribuée.
+
*Pour résoudre* : ajoutez plus de capacité provisionnée.

* *SliceServiceUnHealthy*: Le système a détecté qu'un service de tranche est malsain et le met automatiquement hors service.
+
** Gravité = Avertissement : aucune action n'est entreprise. Ce délai d'avertissement expire dans 6 minutes.
** Gravité = erreur : le système met automatiquement hors service les données et reréplique ses données sur d'autres lecteurs en bon état.


+
*Pour résoudre* : recherchez des problèmes de connectivité réseau et des erreurs matérielles. Il y aura d'autres défauts si des composants matériels spécifiques sont défectueux. Le défaut s'efface lorsque le service de tranche est accessible ou lorsque le service a été mis hors service.

* *SshEnabled* : le service SSH est activé sur un ou plusieurs nœuds du cluster de stockage.
+
*Pour résoudre* : désactivez le service SSH sur le ou les nœuds appropriés ou contactez le support NetApp pour obtenir de l'aide.

* *SslCertificateExexpiration* : le certificat SSL associé à ce nœud arrive à expiration ou a expiré. Ce défaut utilise les niveaux de gravité suivants en fonction de l'urgence :
+
[cols="25,75"]
|===
| Gravité | Description 


| Avertissement | Le certificat expire dans un délai de 30 jours. 


| Erreur | Le certificat expire dans un délai de 7 jours. 


| Primordial | Le certificat expire dans un délai de 3 jours ou a déjà expiré. 
|===
+
*Pour résoudre* : renouveler le certificat SSL. Si nécessaire, contactez le support NetApp pour obtenir de l'aide.

* *StrandedCapacity* : un seul nœud représente plus de la moitié de la capacité du cluster de stockage. Afin de préserver la redondance des données, le système réduit la capacité du nœud le plus grand, de sorte qu'une partie de sa capacité de bloc soit inutilisée.
+
*Pour résoudre* : ajoutez des lecteurs à des nœuds de stockage existants ou ajoutez des nœuds de stockage au cluster.

* *TempSensor*: Un capteur de température signale des températures supérieures à la normale. Cette anomalie peut être déclenchée en même temps que les pannes de l'alimentation électrique ou du ventilateur.
+
*Pour résoudre* : vérifiez si le débit d'air n'est pas obstrué à proximité du bloc d'instruments. Si nécessaire, contactez le support NetApp pour obtenir de l'aide.

* *Mise à niveau*: Une mise à niveau a été en cours depuis plus de 24 heures.
+
*Pour résoudre* : reprenez la mise à niveau ou contactez le support NetApp pour obtenir de l'aide.

* *Non réactif Service*: Un service ne répond plus.
+
*À résoudre* : contactez le support NetApp pour obtenir de l'aide.

* *VirtualNetworkConfig* : cette erreur de cluster indique l'une des conditions suivantes :
+
** Aucune interface n'est présente.
** Un namespace incorrect sur une interface.
** Le masque de réseau est incorrect.
** L'adresse IP est incorrecte.
** Une interface n'est pas opérationnelle.
** Il y a une interface superflue sur un noeud.


+
*À résoudre* : contactez le support NetApp pour obtenir de l'aide.

* *VolumesDegaded*: Les volumes secondaires n'ont pas terminé la réplication et la synchronisation. Le message est effacé lorsque la synchronisation est terminée.
* *VolumesOffline* : un ou plusieurs volumes du cluster de stockage sont hors ligne. L'erreur « volume Degraded » est également présente.
+
*À résoudre* : contactez le support NetApp pour obtenir de l'aide.





== Trouvez plus d'informations

* https://docs.netapp.com/us-en/hci/index.html["Documentation NetApp HCI"^]
* https://www.netapp.com/data-storage/solidfire/documentation["Page Ressources SolidFire et Element"^]

